# Generated by Django 4.0 on 2022-08-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_postal_code_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
