# Generated by Django 4.0 on 2022-03-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_slug_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoty',
            new_name='category',
        ),
    ]
