# Generated by Django 4.0 on 2022-03-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_product_available_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='product_variant',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size_variant',
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.color'),
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.size'),
        ),
    ]
