# Generated by Django 4.0 on 2022-03-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_color_variant_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='size_variant',
            new_name='size',
        ),
    ]
