# Generated by Django 4.0 on 2022-03-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_product_like_product_unlike_product_unlike_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unlike_count',
        ),
    ]
