# Generated by Django 4.0 on 2022-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_product_change_variant_update_pricetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_price',
            field=models.IntegerField(default=0),
        ),
    ]
