# Generated by Django 4.0 on 2022-08-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_product_pre_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='change',
            new_name='is_changed',
        ),
        migrations.AddField(
            model_name='variant',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
