# Generated by Django 4.0 on 2022-08-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_change_product_is_changed_variant_is_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Size', 'size'), ('Color', 'color')], max_length=30, null=True),
        ),
    ]
