# Generated by Django 4.0 on 2022-09-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0033_product_viewcount_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='poducts_view', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
