# Generated by Django 4.0 on 2022-09-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_product_favourite_users_delete_favourite'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='favourite_users',
        # ),
    ]
