# Generated by Django 4.0 on 2022-09-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_product_favourite_users_favourite'),
    ]

    operations = [
    ]
