# Generated by Django 4.0 on 2022-09-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20220911_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourite_users',
        ),
    ]
