# Generated by Django 4.0 on 2022-09-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_product_favourite_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourite_users',
        ),
    ]
