# Generated by Django 4.0 on 2022-09-11 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0044_remove_product_favourite_users_variant_pre_price'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='variant',
        #     name='pre_price',
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='fav_users',
        #     field=models.ManyToManyField(blank=True, related_name='favs', to=settings.AUTH_USER_MODEL),
        # ),
    ]
