# Generated by Django 4.0 on 2022-09-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_favourite'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='product',
        #     old_name='favourite_users',
        #     new_name='fav_users',
        # ),
    ]
