# Generated by Django 4.0 on 2022-08-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_is_email_active_profile_is_phone_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prfile_image',
            field=models.ImageField(blank=True, default='profile/profile.jpg', null=True, upload_to='profile/'),
        ),
    ]
