# Generated by Django 4.0 on 2022-08-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_prfile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
