# Generated by Django 4.0 on 2022-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sessionkey',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
