# Generated by Django 4.0 on 2022-03-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_product_variant_variant_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='color',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='size',
            new_name='size_variant',
        ),
    ]
