# Generated by Django 4.0 on 2022-03-27 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_color_variant_variant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
