# Generated by Django 4.0 on 2022-07-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_product_like_alter_product_unlike_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.color'),
        ),
    ]
