# Generated by Django 4.0 on 2022-08-12 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_product_favourite_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ بندی', 'verbose_name_plural': 'رنگ بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز بندی', 'verbose_name_plural': 'سایز بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'گونه', 'verbose_name_plural': 'گونه ها'},
        ),
        migrations.AlterField(
            model_name='product',
            name='favourite_users',
            field=models.ManyToManyField(blank=True, related_name='favourits', to=settings.AUTH_USER_MODEL),
        ),
    ]
