# Generated by Django 4.0 on 2022-08-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_brand_product_color_product_size_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sellcount',
            field=models.IntegerField(default=0),
        ),
    ]
