# Generated by Django 4.0 on 2022-09-04 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0032_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, related_name='poducts_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
