# Generated by Django 4.0 on 2022-09-11 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


def create_through_relations(apps, schema_editor):
    Group = apps.get_model('Product', 'User')
    Membership = apps.get_model('Product', 'Favourite')
    for group in Group.objects.all():
        for member in group.members.all():
            Membership(
                person=member,
                group=group,
                date_joined=datetime.date.today()
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0037_remove_product_favourite_users'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='product',
        #     name='favourite_users',
        #     field=models.ManyToManyField(blank=True, related_name='favourits', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.CreateModel(
        #     name='Favourite',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('favcount', models.IntegerField(default=0)),
        #         ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
        #         ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
        #     ],
        # ),
    ]
