# Generated by Django 4.0 on 2022-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_product_favourite_users'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='favourite_users',
        # ),
        # migrations.AddField(
        #     model_name='variant',
        #     name='pre_price',
        #     field=models.IntegerField(default=0),
        # ),
    ]
