# Generated by Django 4.0 on 2022-09-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_remove_product_favourite_users_product_favour_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourite_users',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='favourite_users',
        ),
    ]
