# Generated by Django 4.0 on 2022-08-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_coupon_end_alter_coupon_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='codeorder',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
